# Generated by Django 4.2.1 on 2023-06-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment_status_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+123 45 678 90 12', max_length=256, verbose_name='Delivery address'),
        ),
    ]
