# Generated by Django 4.2.1 on 2023-06-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=256, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='+375', max_length=256, verbose_name='Phone'),
        ),
    ]
