# Generated by Django 4.2.1 on 2023-06-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_title_price'),
        ('cart', '0011_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsincart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.title', verbose_name='Book'),
        ),
    ]
