# Generated by Django 4.2.1 on 2023-06-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_itemsincart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
