# Generated by Django 4.2.1 on 2023-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.TextField(default='item', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
