# Generated by Django 4.2.1 on 2023-07-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_order_item_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.TextField(default='item', verbose_name='Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart', verbose_name='Cart'),
        ),
    ]
