# Generated by Django 4.2.1 on 2023-05-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_title_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reference.edition', verbose_name='Edition'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reference.genre', verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='title',
            name='publishing_house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reference.publishinghouse', verbose_name='Publishing house'),
        ),
    ]
