# Generated by Django 4.2.1 on 2023-05-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_alter_publishinghouse_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishinghouse',
            name='country',
            field=models.CharField(max_length=256, verbose_name='Country'),
        ),
    ]
