# Generated by Django 4.2.1 on 2023-05-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_alter_publishinghouse_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.PROTECT, to='reference.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='title',
            name='publishing_house',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='reference.publishinghouse', verbose_name='Publishing house'),
        ),
    ]
