# Generated by Django 4.2.1 on 2023-06-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_title_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=6, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
